name: 'Conan composite action'
description: 'A composite action to handle building a Conan package'

inputs:
  new_tag:
    required: true
    description: 'The new tag to push'
  package-file:
    required: true
    description: 'Path to conanfile.py'
    default: './'
  arch:
    required: true
    description: 'The package arch'
    default: x86_64
outputs:
  package:
    description: 'The new package name and version'
    value: ${{ steps.echo_name.outputs.package_name }}
runs:
    using: "composite"
    steps:
          
      - name: Override version in conanfile.py
        uses: teveltech/version-action@master
        with:
          new_version: ${{ inputs.new_tag }}
          file_path: ${{ inputs.package-file }}
          
      - name: Link conan config directory to github home /github/home
        shell: bash
        run: rm -rf $HOME/.conan && ln -s /root/.conan $HOME
      
      - name: Create conan package
        shell: bash
        run: source /opt/ros/melodic/setup.bash && conan create . _/_ -s arch=${{ inputs.arch }} -s arch_build=${{ inputs.arch }} --build missing -r tevel-conan
        
      - name: Upload conan packages
        shell: bash
        run: conan upload "*" -c -r tevel-conan --all
        
      - name: Echo package name
        id: echo_name
        shell: bash
        run: |
          echo \"$(tac ${{ inputs.package-file }}conanfile.py | grep -e 'name =' -e '__version__ =' | awk -F"[\"\"]" '{printf $2"/"}' | cut -d "/" -f 1,2)\"
          echo "::set-output name=package_name:: \
          $(echo \"$(tac ${{ inputs.package-file }}conanfile.py | grep -e 'name =' -e '__version__ =' | awk -F"[\"\"]" '{printf $2"/"}' | cut -d "/" -f 1,2)\")"
