name: 'Conan composite action'
description: 'A composite action to handle building a Conan package'

inputs:
  new-tag:
    required: true
    description: 'The new tag to push'
  package-folder:
    required: true
    description: 'Path to conanfile.py'
    default: './'
  arch:
    required: true
    description: 'The package arch'
    default: armv8
    
outputs:
  package:
    description: 'The new package name and version'
    value: ${{ steps.echo_name.outputs.package-name }}
    
runs:
    using: "composite"
    steps:
          
      - name: Override version in conanfile.py
        uses: teveltech/version-action@master
        with:
          new_version: ${{ inputs.new-tag }}
          file_path: ${{ inputs.package-folder }}
          
      - name: Link conan config directory to github home /github/home
        shell: bash
        run: rm -rf $HOME/.conan && ln -s /root/.conan $HOME
      - name: remove and create conan profile
        shell: bash
        run: rm -rf /root/.conan/profiles/default && conan profile new default --detect && conan profile update settings.compiler.libcxx=libstdc++11 default
      - name: Upgrade conan and cmake
        shell: bash
        run: pip3 install --upgrade conan cmake
      - name: Create conan package
        shell: bash
        working-directory: ${{ inputs.package-folder }}
        run: source /opt/ros/noetic/setup.bash && conan create . _/_ -s arch=${{ inputs.arch }} -s arch_build=${{ inputs.arch }} --build missing -r tevel-conan
        
      - name: Upload conan packages
        shell: bash
        working-directory: ${{ inputs.package-folder }}
        run: conan upload "*" -c -r tevel-conan --all
        
      - name: Echo package name
        id: echo_name
        shell: bash
        run: |
          echo \"$(tac ${{ inputs.package-folder }}conanfile.py | grep -e 'name =' -e '__version__ =' | awk -F"[\"\"]" '{printf $2"/"}' | cut -d "/" -f 1,2)\"
          echo "::set-output name=package-name:: \
          $(echo \"$(tac ${{ inputs.package-folder }}conanfile.py | grep -e 'name =' -e '__version__ =' | awk -F"[\"\"]" '{printf $2"/"}' | cut -d "/" -f 1,2)\")"
